"""Initial migration

Revision ID: e52229d3ebd3
Revises: eaa44b944665
Create Date: 2023-12-12 00:50:07.459103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e52229d3ebd3'
down_revision = 'eaa44b944665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('RESPONSE', sa.String(length=255), nullable=True),
    sa.Column('LEVEL', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('your_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('your_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('RESPONSE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('LEVEL', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('data_training')
    # ### end Alembic commands ###
